### ISSUE TITLE
Markbot doesn't see existing background

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/frozen-not-in-time#1]
Hello, @thomasjbradley!

I have started on the assignment and wanted to see if my background matching the screenshots, but Markbot sees my website page completely white, even though I can see the linear gradient in my browser.

**Comment by thomasjbradley** [comment]
It’s because of the syntax you’re using for the colour stops in the gradient. Double position colour stops, like `#d4fdff 0px 20px` were not introduced into Chrome until version 77. Markbot is unfortunately using an older version, 66, which doesn’t support double position stops.

You’ll have to play around with the linear gradient to use only 1 pixel value after each colour.

**Comment by anna-pokhilenko** [comment]
Oh, got it. Thank you) 
I also have one button problem and another weird Markbot problem. 

For the button, I cannot change its settings in terms of border-colour and text colour. I have tried everything I did in the last assignments and it used to work fine for me, but, in that case, it doesn't work in the browser.

And for the Markbot, it doesn't see how my background adjusts when I use h-w-1 or h-w-1-2 classes. I can see it in the browser, but Markbot won't see it for some reason.

**Comment by thomasjbradley** [comment]
Have you committed & pushed? I don’t see the button online.

**Comment by anna-pokhilenko** [comment]
Oops. Just pushed it!

**Comment by thomasjbradley** [comment]
*Re: button—*

The CSS is out of order inside `<head>`:
https://github.com/anna-pokhilenko/frozen-not-in-time/blob/gh-pages/index.html#L7-L10
Should be `modules`, `grid`, `type`, `main`.

*Because `main.css` is at the top it cannot overwrite CSS from the files that come after it.*

**Comment by thomasjbradley** [comment]
*Re: height—*

It looks like, in my code, I’m not setting a `min-height` on the banner. I’m using the icecream cone to define the height of the banner. I have `min-height: 480px` on the `<div>` that surrounds the icecream cone & that is creating the banner’s height.

**Comment by anna-pokhilenko** [comment]
Oh wow, I knew that the order was there for some reason, but I never knew why it's important. 

Great, I'll do that instead!

Thank you)

**Comment by anna-pokhilenko** [comment]
Hello, @thomasjbradley!

I am working on that assignment again and I was wondering if it is a good practice to insert SVGs as a code or it would be fine if I just used img tag for these ones?

I also have a bit of a problem with the right sizing of the svg files. When I upload them as they are with <svg width="256" height="256"...> they appear bigger than you wanted them to be, but when I change the sizing according to the properties I see on inspection, they become smaller than expected. 

Finally, I have a problem with z-index. It will not work if I use it.

Thanks!

**Comment by thomasjbradley** [comment]
> I was wondering if it is a good practice to insert SVGs as a code or it would be fine if I just used img tag for these ones?

It really depends on what you want to do with the SVG.
- If you want to add transitions & animations to different parts within the same SVG, then you need to insert the code
- If you want to treat the SVG as a single blob, then use an `<img>` tag
For this assignment `<img>` tags work perfectly.

**Comment by thomasjbradley** [comment]
> I also have a bit of a problem with the right sizing of the svg files. When I upload them as they are with <svg width="256" height="256"...> they appear bigger than you wanted them to be, but when I change the sizing according to the properties I see on inspection, they become smaller than expected.

Maybe this is because they have been inserted as code.

**Comment by thomasjbradley** [comment]
> Finally, I have a problem with z-index. It will not work if I use it.

Are you applying `position: relative` or `position: absolute` to the elements?
